module.exports = {
    send_data:"Please send proper data",
    max_otp_send :"You have tried maximum no. of otp, so your number is blocked. Please contact showkit admin for further query",
    otp_expired :"OTP is expired",
    error_save_data: "Error in saveing data",
    server_error:"Server Error",
    showkt_exist:"This showkt id is already exists",
    phone:"Phone number does not exists",
    register_msg : "Thank you for register. Please verify your phone",
    user_exist : "User is exist with this phone number.",
    user_not_exist : "Phone number does not exists",
    otp_sent : "OTP sent to your mobile number",
    otp_not_match : "OTP does not match",
    user_verify : "User verified successfully",
    token_expired :"Token is expired.",
    user_not_verify: 'User is not active. Please verify your phone number first',
    invalid_pass : "Authentication Failed, Invalid Passcode.",
    login_success:"Logged in successfully.",
    payment_complete:"Payment completed",
    payment_error:"Error in payment",
    clinic_book_error:"Error in book click",
    clinic_book_success:"your booking is confirmed",
    check_email:"Please check your registered mail account.",
    invalid_code:"Invalid code",
    password_set_error:"Error in password set",
    password_set_success:"Password set successfully.",
    apple_error:"Apple login error",
    submit_email:"Error in register email",
    review_msg:"Review has been subbmitted successfully",
    review_error:"Error in review submit",
    auth_user_error : "You are not authorised user",
    old_password_error:"Old password does not match in our database",
    pass_update_error :"Error in password update",
    pass_update_success : "Password has been successfully",
    user_profile_update :"Profile has been updated successfully",
    user_profile_update_error :"Profile has been updated successfully",
    card_save_error :"Error in card save",
    quest_save_error : "Error in save questionnaires",
    subbmittted_success:"Data submitted successfully",
    promocode_used : "This promocode is already used for this service",
    invalid_used : "Invalid code or Code does not exists",
    error_submit_from: 'Error in submit form',
    submit_success : "Form submitted successfully",
    no_data : "'No updated available'",
    data_available : "Data is available",
    error_delete_card : 'Error in delete card',
    delete_card :'Card deleted',
    error_notification_update : 'Error in notification update',
    success_notification_update:'Notification update succesfully',
    upcom_appoint:'Your upcoming appointment',
    reminder_notification:'Reminder Notification',
    already_added:'This card is already added in list',
    invalid_card:"Card is not valid or use another card",
    noti_new_service_text : "We are launching new experiences in ALBYA, tap here to learn more about",
    noti_new_service_title : "New service information",
    twohr_noti_text :"Your doctor is waiting for you in a couple of hours",
    tfhr_noti_text :"Soon! Remember you have an appointment with your doctor tomorrow",
    daily_noti_text :"We know is hard to improve, your ALBYA cart is still waiting for you",
    reminder : "Reminder from Albya",
    clinic_not_choose : "We know is hard to improve, your ALBYA cart is still waiting for you",
    complete_booking : "Completed your booking",
    review_notify_text : "We want to know, how was your ALBYA experience?",
    hr_noti_title : "Your doctor is waiting",
    service_clinic_assign_error : "Error in assign clinic",
    service_clinic_assign_success : "Clinic assigned successfully"
};